// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABR8uEH4xG1uOn31AlgvvhglpMd6rsFEg',
    appId: '1:64129881421:android:bbb3f56ecedf679fcd9304',
    messagingSenderId: '64129881421',
    projectId: 'busmate-54bb3',
    databaseURL: 'https://busmate-54bb3-default-rtdb.firebaseio.com',
    storageBucket: 'busmate-54bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQqpl5tsYbAbjSPyvJS9-wVcjauPBM3YY',
    appId: '1:64129881421:ios:0d45a4c7ccdaea04cd9304',
    messagingSenderId: '64129881421',
    projectId: 'busmate-54bb3',
    databaseURL: 'https://busmate-54bb3-default-rtdb.firebaseio.com',
    storageBucket: 'busmate-54bb3.firebasestorage.app',
    iosBundleId: 'com.example.busmateUpdated',
  );

}